// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csrbncucopdypzglwdcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzcmJuY3Vjb3BkeXB6Z2x3ZGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDkxOTUsImV4cCI6MjA2ODY4NTE5NX0.5fvp23uGGmhbzVFHAqrT6EclxyeG205sOg3A2OvQSRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});